import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PrivyProvider } from "@privy-io/react-auth";
import { defineChain } from "viem";
import { sepolia } from "viem/chains";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const BitTorrentTestnet = defineChain({
  id: 1029,
  name: "BitTorrent Testnet",
  nativeCurrency: { name: "BTT", symbol: "BTT", decimals: 18 },
  rpcUrls: {
    default: { http: ["https://pre-rpc.bt.io/"] },
  },
  blockExplorers: {
    default: { name: "BitTorrent Explorer", url: "https://testscan.bt.io" },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PrivyProvider
          appId="your-privy-app-id"
          clientId="your-app-client-id"
          config={{
            // Create embedded wallets for users who don't have a wallet
            embeddedWallets: {
              createOnLogin: "users-without-wallets",
            },
            defaultChain: BitTorrentTestnet,
            supportedChains: [sepolia, BitTorrentTestnet],
          }}
        >
          {children}
        </PrivyProvider>
      </body>
    </html>
  );
}
